# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c98f276a6f36f0c2fe9eaa18d07abdba0fc553bf6b8e07baa1c34523a5ba2758443ca5c9c1890b6a4d776572651768ea66b07455bce9c750a305cb9c80c5add

test:
  secret_key_base: d0e2f8bf442d05e9567d7f52d79f5ac7e654f75938474fb321179c1d672bbb2e74044fcbd54df10ea5e782feaf588147c40e6ab2ee0ddc694310025329e62571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7c98f276a6f36f0c2fe9eaa18d07abdba0fc553bf6b8e07baa1c34523a5ba2758443ca5c9c1890b6a4d776572651768ea66b07455bce9c750a305cb9c80c5add
